on:
  push:
    tags:
      - "v*.*.*"
name: release-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Checkout tag
        run: |
          tag_name="${GITHUB_REF##*/}"
          echo Tag $tag_name
          git checkout $tag_name
          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV

      - name: Build
        run: |
          make release -j$(nproc)

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          file: ./trojan-go-*.zip
          file_glob: true
          prerelease: true
